import {useEffect,useState} from 'react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {supabase} from '@/lib/supabase';
import type {Session} from '@supabase/supabase-js';
import './admin.css';
type Event={id:string;name:string;spot:string;start:string;end:string;quantity:number;status:string};
type Ad={id:string;name:string;placement:string;url:string;start:string;end:string;image:string;status:string};
type Message={id:string;title:string;body:string;audience:string;time:string;status:string};
type Claim={id:string;event:string;status:string};
type Data={events:Event[];ads:Ad[];messages:Message[];claims:Claim[];log:string[]};
type DrawCampaign={id:string;reward_label:string;total_inventory:number|null;drawn_at:string|null};
type DrawEntryRow={reservation_id:string;email:string;status:string;created_at:string};
type WinnerRow={reservation_id:string;email:string;status:string;shipping:{recipient:string;phone:string;zip:string;address:string}|null;updated_at:string};
type DrawInfo={campaign:DrawCampaign;entries:DrawEntryRow[];winners:WinnerRow[]};
const winnerStatusLabel=(s:string)=>({WON:'당첨 확인 대기',WINNER_ACTION_REQUIRED:'당첨 확인 진행 중',VERIFIED:'본인 확인 완료 · 배송 입력 대기',FULFILLING:'배송 준비 중',DELIVERED:'배송 완료'} as Record<string,string>)[s]||s;
const seed:Data={events:[{id:'demo-magok',name:'마곡 나이트 드롭',spot:'마곡 · 관람 지점 확인 필요',start:'',end:'',quantity:100,status:'초안'}],ads:[],messages:[],claims:[{id:'DEMO-001',event:'마곡 · 예시',status:'수령 정보 대기'},{id:'DEMO-002',event:'마곡 · 예시',status:'지급 결과 확인 중'},{id:'DEMO-003',event:'마곡 · 예시',status:'배송 준비'}],log:[]};
const blankEvent={id:'',name:'',spot:'코엑스 케이팝스퀘어',start:'',end:'',quantity:100,status:'초안'};
const blankAd={id:'',name:'',placement:'에피소드 피드',url:'',start:'',end:'',image:'',status:'초안'};
const blankMessage={id:'',title:'',body:'',audience:'마케팅 동의 회원 · 예시',time:'',status:'초안'};
export default function Admin(){
 const [data,setData]=useState<Data>(seed),[ready,setReady]=useState(false),[tab,setTab]=useState('events'),[form,setForm]=useState<'event'|'ad'|'message'|null>(null),[event,setEvent]=useState<Event>(blankEvent),[ad,setAd]=useState<Ad>(blankAd),[message,setMessage]=useState<Message>(blankMessage),[error,setError]=useState(''),[notice,setNotice]=useState(''),[confirm,setConfirm]=useState<{kind:'pause'|'claim'|'message';id:string}|null>(null);
 // 실제 로그인 · 관리자 권한 확인 (localStorage 목업과 별개로, 진짜 Supabase 계정 + is_admin 플래그를 확인한다)
 const [session,setSession]=useState<Session|null>(null),[authReady,setAuthReady]=useState(false),[isAdmin,setIsAdmin]=useState<boolean|null>(null);
 const [loginEmail,setLoginEmail]=useState(''),[loginSent,setLoginSent]=useState(false),[loginError,setLoginError]=useState('');
 // 실제 추첨(서버) 상태 — 캠페인별 응모 현황과 당첨자
 const [draws,setDraws]=useState<Record<string,DrawInfo>>({}),[drawBusy,setDrawBusy]=useState(false),[drawConfirm,setDrawConfirm]=useState<string|null>(null),[drawError,setDrawError]=useState('');
 const [deliverBusy,setDeliverBusy]=useState<string|null>(null);
 useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session);setAuthReady(true)});const {data:sub}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return ()=>sub.subscription.unsubscribe()},[]);
 useEffect(()=>{if(!session){setIsAdmin(null);return}supabase.from('profiles').select('is_admin').eq('id',session.user.id).maybeSingle().then(({data})=>setIsAdmin(data?.is_admin===true))},[session]);
 async function loadDraws(){
  const {data:campaignRows}=await supabase.from('campaigns').select('id,reward_label,total_inventory,drawn_at,code,reward_mode').eq('reward_mode','draw');
  const next:Record<string,DrawInfo>={};
  for(const c of campaignRows||[]){
   if(!c.code)continue; // 응모 코드가 없는(아직 확정되지 않은) 캠페인은 실제 응모 자체가 없으므로 표시하지 않는다
   const {data:entryRows}=await supabase.rpc('admin_list_entries',{p_campaign_id:c.id});
   let winnerRows:WinnerRow[]=[];
   if(c.drawn_at){const {data:w}=await supabase.rpc('admin_list_winners',{p_campaign_id:c.id});winnerRows=(w||[]) as WinnerRow[]}
   next[c.id]={campaign:c,entries:(entryRows||[]) as DrawEntryRow[],winners:winnerRows};
  }
  setDraws(next);
 }
 async function markDelivered(reservationId:string){
  setDeliverBusy(reservationId);
  const {error}=await supabase.rpc('admin_mark_delivered',{p_reservation_id:reservationId});
  setDeliverBusy(null);
  if(error){setDrawError('발송 완료 처리에 실패했습니다: '+error.message);return}
  setNotice('발송 완료로 표시했습니다.');
  loadDraws();
 }
 useEffect(()=>{if(isAdmin)loadDraws()},[isAdmin]);
 async function runDraw(id:string){
  setDrawBusy(true);setDrawError('');
  const {error}=await supabase.rpc('run_draw',{p_campaign_id:id});
  setDrawBusy(false);setDrawConfirm(null);
  if(error){setDrawError(error.message==='ALREADY_DRAWN'?'이미 추첨이 완료된 캠페인입니다.':error.message==='NOT_ADMIN'?'관리자 권한이 없습니다.':'추첨 실행에 실패했습니다: '+error.message);return}
  setNotice('추첨을 실행했습니다. 당첨자에게 실제로 반영됩니다.');
  loadDraws();
 }
 function sendLoginLink(){setLoginError('');supabase.auth.signInWithOtp({email:loginEmail.trim(),options:{emailRedirectTo:window.location.origin+'/admin',shouldCreateUser:false}}).then(({error})=>{if(error){setLoginError('메일 전송에 실패했어요. 관리자로 등록된 이메일인지 확인해주세요.');return}setLoginSent(true)})}
 useEffect(()=>{try{const raw=JSON.parse(localStorage.getItem('seeson-admin-demo-v1')||'null');if(raw&&Array.isArray(raw.events)&&Array.isArray(raw.ads)&&Array.isArray(raw.messages)&&Array.isArray(raw.claims)&&Array.isArray(raw.log))setData(raw)}catch{}setReady(true)},[]);
 useEffect(()=>{if(ready)try{localStorage.setItem('seeson-admin-demo-v1',JSON.stringify(data))}catch{setNotice('저장 공간이 부족해 이번 변경은 새로고침 후 유지되지 않을 수 있습니다.')}},[data,ready]);
 function change(fn:(prev:Data)=>Data,action:string){setData(prev=>{const next=fn(prev);return {...next,log:[new Date().toLocaleString('ko-KR')+' · '+action,...prev.log].slice(0,40)}});setNotice(action+' · 데모 저장 완료')}
 function openForm(kind:'event'|'ad'|'message'){setError('');setForm(kind)}
 function dates(start:string,end:string){return !!start&&!!end&&new Date(end)>new Date(start)}
 function saveEvent(){if(!event.name.trim()||!event.spot.trim()||!Number.isInteger(event.quantity)||event.quantity<1){setError('이름·장소와 1개 이상의 정수 수량을 입력해주세요.');return}if((event.start||event.end)&&!dates(event.start,event.end)){setError('종료 시간을 시작 시간 이후로 지정해주세요.');return}const item={...event,id:event.id||crypto.randomUUID()};change(d=>({...d,events:[...d.events.filter(e=>e.id!==item.id),item]}),'이벤트 저장');setForm(null)}
 function saveAd(){try{const u=new URL(ad.url);if(u.protocol!=='https:'||u.username||u.password)throw Error()}catch{setError('연결 주소는 유효한 HTTPS 주소여야 합니다.');return}if(!ad.name.trim()||!ad.image||!dates(ad.start,ad.end)){setError('광고명·이미지·유효한 노출 기간을 입력해주세요.');return}const item={...ad,id:ad.id||crypto.randomUUID(),status:'검수 대기'};change(d=>({...d,ads:[...d.ads.filter(a=>a.id!==item.id),item]}),'광고 검수 요청');setForm(null)}
 function upload(file?:File){if(!file)return;if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>700000){setError('PNG·JPG·WebP, 700KB 이하 파일을 선택해주세요.');return}const reader=new FileReader();reader.onload=()=>{setAd(a=>({...a,image:String(reader.result)}));setError('')};reader.onerror=()=>setError('파일을 읽지 못했습니다.');reader.readAsDataURL(file)}
 function saveMessage(){if(!message.title.trim()||!message.body.trim()||!message.time||new Date(message.time)<=new Date()){setError('제목·내용과 미래의 예약 시간을 입력해주세요.');return}const item={...message,id:message.id||crypto.randomUUID(),status:'초안'};change(d=>({...d,messages:[...d.messages.filter(m=>m.id!==item.id),item]}),'알림 초안 저장');setForm(null)}
 function commit(){if(!confirm)return;if(confirm.kind==='pause')change(d=>({...d,events:d.events.map(e=>e.id===confirm.id?{...e,status:'중지'}:e)}),'신규 접수 중지 체험');if(confirm.kind==='claim')change(d=>({...d,claims:d.claims.map(c=>c.id===confirm.id?{...c,status:'확인 요청됨'}:c)}),'지급 확인 요청 체험');if(confirm.kind==='message')change(d=>({...d,messages:d.messages.map(m=>m.id===confirm.id?{...m,status:'예약됨 · 데모'}:m)}),'알림 예약 체험');setConfirm(null)}
 if(!authReady)return <div className="admin-app admin-loading">불러오는 중…</div>;
 if(!session)return <div className="admin-app"><div className="admin-top"><a href="/" className="admin-brand">시선 <span>STUDIO</span></a><a href="/">사용자 앱 ↗</a></div><div className="admin-login"><h1>관리자 로그인</h1>{loginSent?<p>{loginEmail} 로 로그인 링크를 보냈어요. 메일함(스팸함 포함)에서 링크를 눌러주세요.</p>:<><p>관리자로 등록된 이메일을 입력하면 로그인 링크를 보내드려요. 비밀번호가 필요 없어요.</p><input type="email" value={loginEmail} onChange={e=>setLoginEmail(e.target.value)} placeholder="you@example.com" autoComplete="email"/><button className="admin-save" disabled={!loginEmail.trim()} onClick={sendLoginLink}>로그인 링크 받기</button></>}{loginError&&<p className="admin-error" role="alert">{loginError}</p>}</div></div>;
 if(isAdmin===null)return <div className="admin-app admin-loading">권한 확인 중…</div>;
 if(isAdmin===false)return <div className="admin-app"><div className="admin-top"><a href="/" className="admin-brand">시선 <span>STUDIO</span></a><a href="/">사용자 앱 ↗</a></div><div className="admin-login"><h1>관리자 권한이 없는 계정이에요</h1><p>{session.user.email} 계정은 관리자로 등록되어 있지 않습니다. 관리자 등록이 필요하면 운영팀에 문의해주세요.</p><button className="admin-save" onClick={()=>supabase.auth.signOut()}>다른 계정으로 로그인</button></div></div>;
 return <div className="admin-app"><div className="admin-top"><a href="/" className="admin-brand">시선 <span>STUDIO</span></a><div style={{display:'flex',gap:14,alignItems:'center'}}><span>{session.user.email}</span><button onClick={()=>supabase.auth.signOut()}>로그아웃</button><a href="/">사용자 앱 ↗</a></div></div><div className="admin-intro"><div><p>OPERATIONS / BETA</p><h1>도시의 이야기를 운영하다.</h1></div><span className="admin-tag">관리자 인증됨</span></div><div className="admin-banner">이벤트 · 광고 · 알림 탭은 아직 이 브라우저에만 저장되는 목업입니다. 당첨·지급 탭의 "실제 추첨" 섹션만 실제 서버에 반영됩니다 — 신중하게 사용하세요.</div><Tabs value={tab} onValueChange={v=>setTab(String(v))}><TabsList className="admin-tabs">{[['events','이벤트'],['claims','당첨·지급'],['ads','광고 배너'],['messages','알림']].map(([id,label])=><TabsTrigger key={id} value={id}>{label}</TabsTrigger>)}</TabsList>
<TabsContent value="events"><section className="admin-panel"><div className="admin-panel-head"><div><h2>이벤트 관리</h2><p>초안부터 종료까지, 송출과 수량을 한곳에서.</p></div><button disabled={!ready} onClick={()=>{setEvent(blankEvent);openForm('event')}}>+ 이벤트</button></div><div className="admin-grid">{data.events.map(e=><article className="admin-card" key={e.id}><span className="admin-tag">{e.status}</span><h3>{e.name}</h3><p>{e.spot}</p><dl><div><dt>체험 수량</dt><dd>{e.quantity}개</dd></div><div><dt>시작</dt><dd>{e.start.replace('T',' ')||'미정'}</dd></div><div><dt>종료</dt><dd>{e.end.replace('T',' ')||'미정'}</dd></div></dl><div className="admin-actions"><button onClick={()=>{setEvent(e);openForm('event')}}>수정</button><button disabled={!dates(e.start,e.end)||e.status==='진행 체험'} onClick={()=>change(d=>({...d,events:d.events.map(x=>x.id===e.id?{...x,status:'진행 체험'}:x)}),'진행 상태 체험')}>진행 체험</button><button disabled={e.status==='중지'} onClick={()=>setConfirm({kind:'pause',id:e.id})}>긴급 중지</button><button disabled={e.status==='종료'} onClick={()=>change(d=>({...d,events:d.events.map(x=>x.id===e.id?{...x,status:'종료'}:x)}),'종료 상태 체험')}>종료</button></div></article>)}</div><p className="admin-note">진행 상태는 UI 체험입니다. 실제 공개 전에는 장소·계약·상품·예산 검증과 서버의 시간/재고 판정이 필요합니다.</p></section></TabsContent>
<TabsContent value="claims"><section className="admin-panel"><div className="admin-panel-head"><div><h2>실제 추첨 실행</h2><p>여기서 실행한 추첨만 실제 응모자의 당첨 여부로 서버에 반영됩니다. 한 캠페인당 한 번만 실행할 수 있고, 되돌릴 수 없습니다.</p></div></div>{drawError&&<p className="admin-error" role="alert">{drawError}</p>}<div className="admin-draw-list">{Object.keys(draws).length===0&&<div className="admin-empty">실제 응모 코드가 연결된 추첨형 캠페인이 아직 없습니다.</div>}{Object.values(draws).map(({campaign,entries,winners})=>{const entered=entries.filter(e=>e.status==='ENTERED');const won=entries.filter(e=>e.status==='WON');const notSelected=entries.filter(e=>e.status==='NOT_SELECTED');return <article className="admin-card" key={campaign.id}><span className="admin-tag">{campaign.drawn_at?'추첨 완료':'응모 접수 중'}</span><h3>{campaign.reward_label}</h3><p>정원 {campaign.total_inventory??'무제한'}명 · 실제 응모 {entries.length}명</p>{campaign.drawn_at?<div className="admin-draw-entries"><p><strong>당첨 {won.length}명</strong></p>{winners.map(w=><div key={w.reservation_id} className="admin-winner-row"><p>🏆 {w.email} · {winnerStatusLabel(w.status)}</p>{w.shipping?<p className="admin-winner-address">{w.shipping.recipient} · {w.shipping.phone} · {w.shipping.zip} · {w.shipping.address}</p>:<p className="admin-winner-address">배송 정보 입력 대기 중</p>}{w.status==='FULFILLING'&&<button disabled={deliverBusy===w.reservation_id} onClick={()=>markDelivered(w.reservation_id)}>{deliverBusy===w.reservation_id?'처리 중…':'발송 완료 처리'}</button>}</div>)}<p style={{marginTop:10}}><strong>미당첨 {notSelected.length}명</strong></p>{notSelected.map(w=><p key={w.reservation_id}>{w.email}</p>)}</div>:<div className="admin-actions"><button disabled={!entered.length||drawBusy} onClick={()=>setDrawConfirm(campaign.id)}>추첨 실행 ({entered.length}명 응모 중)</button></div>}</article>})}</div><div className="admin-info"><h3>당첨자에게만 필요한 정보를</h3><p>추첨을 실행하면 당첨자가 본인 확인과 배송 정보 입력을 거쳐 여기 실시간으로 표시됩니다. 발송을 마치면 "발송 완료 처리" 버튼을 눌러주세요 — 한 번 처리하면 되돌릴 수 없습니다.</p></div><div className="admin-panel-head" style={{marginTop:40}}><div><h2>예시 데이터 (이전 목업)</h2><p>아래 표는 실제 데이터가 아닌, 화면 흐름 확인용 가상 기록입니다.</p></div><span className="admin-tag">실제 응모자 0명</span></div><div className="admin-table-wrap"><table><thead><tr><th>참조 ID</th><th>이벤트</th><th>상태</th><th>확인</th></tr></thead><tbody>{data.claims.map(c=><tr key={c.id}><td>{c.id}</td><td>{c.event}</td><td>{c.status}</td><td><button disabled={c.status==='확인 요청됨'} onClick={()=>setConfirm({kind:'claim',id:c.id})}>확인 요청</button></td></tr>)}</tbody></table></div></section></TabsContent>
<TabsContent value="ads"><section className="admin-panel"><div className="admin-panel-head"><div><h2>광고 배너</h2><p>소재와 위치, 기간을 설정하고 노출 전 확인하세요.</p></div><button disabled={!ready} onClick={()=>{setAd(blankAd);openForm('ad')}}>+ 배너</button></div>{data.ads.length===0?<div className="admin-empty">아직 등록된 배너가 없습니다.<p>이미지를 올려 모바일 배너를 미리 확인해보세요.</p></div>:<div className="admin-grid">{data.ads.map(a=><article className="admin-card" key={a.id}><div className="admin-ad-preview"><img src={a.image} alt={a.name}/><span>광고</span></div><h3>{a.name}</h3><p>{a.placement} · {a.status}</p><p>{a.start.replace('T',' ')} ~ {a.end.replace('T',' ')}</p><p>노출 / 클릭: — / — (수집 미연동)</p><div className="admin-actions"><button onClick={()=>{setAd(a);openForm('ad')}}>수정</button><button disabled={a.status!=='검수 대기'} onClick={()=>change(d=>({...d,ads:d.ads.map(x=>x.id===a.id?{...x,status:'승인됨 · 데모'}:x)}),'광고 승인 체험')}>승인</button><button disabled={a.status==='중지'} onClick={()=>change(d=>({...d,ads:d.ads.map(x=>x.id===a.id?{...x,status:'중지'}:x)}),'광고 중지')}>중지</button><a href={a.url} target="_blank" rel="noopener noreferrer">연결 확인 ↗</a></div></article>)}</div>}<p className="admin-note">현재 배너는 이 관리자 미리보기에만 표시됩니다. 사용자 앱 광고 슬롯·서버 검수·성과 수집은 아직 연결되지 않았습니다.</p></section></TabsContent>
<TabsContent value="messages"><section className="admin-panel"><div className="admin-panel-head"><div><h2>알림 관리</h2><p>대상과 내용을 검토하고 발송 예약을 체험하세요.</p></div><button disabled={!ready} onClick={()=>{setMessage(blankMessage);openForm('message')}}>+ 알림</button></div>{data.messages.length===0?<div className="admin-empty">알림 초안이 없습니다.<p>실제 푸시나 문자 발송 없이 예약 화면을 체험합니다.</p></div>:<div className="admin-grid">{data.messages.map(m=><article className="admin-card" key={m.id}><span className="admin-tag">{m.status}</span><h3>{m.title}</h3><p>{m.body}</p><dl><div><dt>대상</dt><dd>{m.audience}</dd></div><div><dt>예약</dt><dd>{m.time.replace('T',' ')}</dd></div><div><dt>실제 발송</dt><dd>0건</dd></div></dl><div className="admin-actions"><button onClick={()=>{setMessage(m);openForm('message')}}>수정</button><button disabled={m.status!=='초안'} onClick={()=>setConfirm({kind:'message',id:m.id})}>예약 확인</button><button disabled={m.status==='취소됨'} onClick={()=>change(d=>({...d,messages:d.messages.map(x=>x.id===m.id?{...x,status:'취소됨'}:x)}),'알림 예약 취소')}>취소</button></div></article>)}</div>}<p className="admin-note">이벤트 홍보는 마케팅 동의, 서비스 안내는 목적에 맞는 발송 근거와 채널 권한을 별도로 확인해야 합니다.</p></section></TabsContent></Tabs>
<details className="admin-audit"><summary>변경 기록 · 이 기기</summary>{data.log.length?data.log.map((l,i)=><p key={i}>{l}</p>):<p>아직 변경 기록이 없습니다.</p>}</details>{notice&&<p className="admin-status" role="status">{notice}</p>}
<Dialog open={form!==null} onOpenChange={v=>{if(!v)setForm(null)}}><DialogContent className="admin-dialog"><DialogTitle>{form==='event'?'이벤트 편집':form==='ad'?'배너 편집':'알림 작성'}</DialogTitle><DialogDescription>목업 전용 · 입력 내용은 현재 브라우저에만 저장됩니다.</DialogDescription><form onSubmit={e=>{e.preventDefault();if(form==='event')saveEvent();else if(form==='ad')saveAd();else saveMessage()}}>
{form==='event'&&<><label>이벤트명<input required maxLength={80} value={event.name} onChange={e=>setEvent({...event,name:e.target.value})}/></label><label>전광판 위치<select value={event.spot} onChange={e=>setEvent({...event,spot:e.target.value})}>{['마곡 · 관람 지점 확인 필요','코엑스 케이팝스퀘어','파르나스 미디어타워','코리아나호텔 K-VISION'].map(x=><option key={x}>{x}</option>)}</select></label><label>체험 수량<input type="number" min="1" max="1000000" required value={event.quantity} onChange={e=>setEvent({...event,quantity:Number(e.target.value)})}/></label><label>시작 · 기기 현지 시간<input type="datetime-local" value={event.start} onChange={e=>setEvent({...event,start:e.target.value})}/></label><label>종료 · 기기 현지 시간<input type="datetime-local" value={event.end} onChange={e=>setEvent({...event,end:e.target.value})}/></label></>}
{form==='ad'&&<><label>광고명<input required maxLength={80} value={ad.name} onChange={e=>setAd({...ad,name:e.target.value})}/></label><label>노출 위치<select value={ad.placement} onChange={e=>setAd({...ad,placement:e.target.value})}>{['에피소드 피드','에피소드 상세 하단','수령 완료 하단'].map(x=><option key={x}>{x}</option>)}</select></label><label>배너 이미지 · 700KB 이하<input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>upload(e.target.files?.[0])}/></label>{ad.image&&<div className="admin-ad-preview"><img src={ad.image} alt="배너 미리보기"/><span>광고</span></div>}<label>연결 주소<input type="url" required placeholder="https://" value={ad.url} onChange={e=>setAd({...ad,url:e.target.value})}/></label><label>노출 시작<input type="datetime-local" required value={ad.start} onChange={e=>setAd({...ad,start:e.target.value})}/></label><label>노출 종료<input type="datetime-local" required value={ad.end} onChange={e=>setAd({...ad,end:e.target.value})}/></label><p className="admin-note">수정 시 다시 검수 대기로 전환됩니다. 스캔·가입·수령 버튼을 가리는 지면은 제공하지 않습니다.</p></>}
{form==='message'&&<><label>제목<input required maxLength={60} value={message.title} onChange={e=>setMessage({...message,title:e.target.value})}/></label><label>내용<textarea required maxLength={300} value={message.body} onChange={e=>setMessage({...message,body:e.target.value})}/></label><label>대상<select value={message.audience} onChange={e=>setMessage({...message,audience:e.target.value})}>{['마케팅 동의 회원 · 예시','당첨자 · 예시','수령 대기자 · 예시'].map(x=><option key={x}>{x}</option>)}</select></label><label>예약 시간<input type="datetime-local" required value={message.time} onChange={e=>setMessage({...message,time:e.target.value})}/></label><div className="admin-info"><small>알림 미리보기</small><h3>{message.title||'제목'}</h3><p>{message.body||'내용'}</p></div></>}
{error&&<p role="alert" className="admin-error">{error}</p>}<button className="admin-save" type="submit">{form==='ad'?'검수 요청 체험':'초안 저장'}</button></form></DialogContent></Dialog>
<Dialog open={confirm!==null} onOpenChange={v=>{if(!v)setConfirm(null)}}><DialogContent className="admin-dialog"><DialogTitle>{confirm?.kind==='pause'?'신규 접수를 중지할까요?':confirm?.kind==='claim'?'지급 확인을 요청할까요?':'알림을 예약할까요?'}</DialogTitle><DialogDescription>{confirm?.kind==='pause'?'데모 이벤트의 상태만 중지로 바뀝니다. 기존 수령 기록은 유지됩니다.':confirm?.kind==='claim'?'가상 기록을 확인 요청 상태로 바꿉니다. 실제 발급·배송 요청은 전송되지 않습니다.':'이 브라우저에 예약 상태를 저장합니다. 예약 시각에 실제 메시지는 발송되지 않습니다.'}</DialogDescription><button className="admin-save" onClick={commit}>확인 · 데모</button><button onClick={()=>setConfirm(null)}>취소</button></DialogContent></Dialog>
<Dialog open={drawConfirm!==null} onOpenChange={v=>{if(!v)setDrawConfirm(null)}}><DialogContent className="admin-dialog"><DialogTitle>정말 추첨을 실행할까요?</DialogTitle><DialogDescription>실제 응모자 전원의 당첨/미당첨이 지금 확정되고, 되돌릴 수 없습니다. 응모가 마감된 뒤에만 실행하세요.</DialogDescription><button className="admin-save" disabled={drawBusy} onClick={()=>drawConfirm&&runDraw(drawConfirm)}>{drawBusy?'실행 중…':'추첨 실행'}</button><button onClick={()=>setDrawConfirm(null)}>취소</button></DialogContent></Dialog>
</div>
}
