import { useEffect,useRef,useState } from 'react';
import { localize, type Language } from '@/lib/i18n';
import { NotificationCenter,sampleNotifications,type InboxItem } from '@/components/notification-center';
import { SpotExplorer } from '@/components/spot-explorer';
import { Bell,ArrowUpRight,ScanLine,MapPin,ArrowRight,Eye,Gift,Sparkles,UserRound,Compass,Check,Clock,ShieldCheck,Ticket,ChevronRight,Camera,Info,CheckCircle2,RotateCcw,Download,Watch,Handbag,Bitcoin,Tag } from 'lucide-react';
import { Tabs,TabsList,TabsTrigger,TabsContent } from '@/components/ui/tabs';
import { Dialog,DialogContent,DialogTitle,DialogDescription } from '@/components/ui/dialog';
import { Checkbox } from '@/components/ui/checkbox';
import { campaigns,initial,revealDraw,drawStatusLabel,drawCta,type DemoState } from '@/lib/demo';
import magok from './assets/magok.jpg';
import { supabase } from '@/lib/supabase';
import type { Session } from '@supabase/supabase-js';
type Modal='payout-error'|'notifications'|'scan'|'detail'|'signup'|'success'|'reset'|'settings'|'spots'|'checking'|'scan-error'|'reward-detail'|'receipt'|'draw-success'|'draw-status'|'draw-verify'|'draw-shipping'|null;
const nav=[{id:'discover',label:'발견',icon:Compass},{id:'scan',label:'스캔',icon:ScanLine},{id:'wallet',label:'내 것',icon:Gift}];
export default function Home(){
 const [tab,setTab]=useState('discover'),[state,setState]=useState<DemoState>(initial),[ready,setReady]=useState(false),[modal,setModal]=useState<Modal>(null),[selected,setSelected]=useState('magok'),[filter,setFilter]=useState('전체'),[code,setCode]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[required,setRequired]=useState(false),[marketing,setMarketing]=useState(false);
 const [inboxRead,setInboxRead]=useState<string[]>([]);const [inboxEvents,setInboxEvents]=useState(false);const [inboxRewards,setInboxRewards]=useState(true);const [inboxReady,setInboxReady]=useState(false);
 useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem('seeson-inbox-v1')||'null');if(saved){setInboxRead(Array.isArray(saved.read)?saved.read.filter((v:unknown)=>typeof v==='string'):[]);setInboxEvents(saved.events===true);setInboxRewards(saved.rewards!==false)}}catch{}setInboxReady(true)},[]);
 useEffect(()=>{if(inboxReady)try{localStorage.setItem('seeson-inbox-v1',JSON.stringify({read:inboxRead,events:inboxEvents,rewards:inboxRewards}))}catch{}},[inboxReady,inboxRead,inboxEvents,inboxRewards]);
 const inboxItems:InboxItem[]=[...state.entries.map(e=>({id:`reward-${e.campaignId}-${e.claimed?'claimed':'reserved'}`,title:e.claimed?'리워드 수령 체험을 완료했어요.':'확보한 리워드가 보관함에 있어요.',body:e.claimed?'보관함에서 수령 내역을 확인하세요. 실제 쿠폰 지급은 없는 데모입니다.':'가입 후 수령 체험을 이어가세요. 실제 쿠폰 지급은 없는 데모입니다.',target:'wallet' as const,sample:false})),...sampleNotifications];
 const inboxUnread=inboxItems.filter(i=>!inboxRead.includes(i.id)).length;
 const [mapSpot,setMapSpot]=useState('coex');const [language,setLanguage]=useState<Language>('ko');const [walletFilter,setWalletFilter]=useState('all');const [rewardId,setRewardId]=useState('magok');const signupReturn=useRef<Modal>('settings');
 const [drawId,setDrawId]=useState('birkin');const [verifyChecked,setVerifyChecked]=useState(false);
 const [comingArea,setComingArea]=useState('전체');const [comingCategory,setComingCategory]=useState('전체');const [shipRecipient,setShipRecipient]=useState('');const [shipPhone,setShipPhone]=useState('');const [shipZip,setShipZip]=useState('');const [shipAddress,setShipAddress]=useState('');
 const [signupEmail,setSignupEmail]=useState('');const [signupSent,setSignupSent]=useState(false);
 useEffect(()=>{try{const saved=localStorage.getItem('seeson-language');if(saved==='en'||saved==='zh-CN'||saved==='ko')setLanguage(saved)}catch{}},[]);
 useEffect(()=>{document.documentElement.lang=language},[language]);
 function chooseLanguage(value:Language){setLanguage(value);try{localStorage.setItem('seeson-language',value)}catch{}}
 function beginSignup(destination:Modal){signupReturn.current=destination;setRequired(false);setMarketing(false);setSignupEmail('');setSignupSent(false);open('signup')}
 function viewReward(id:string){setRewardId(id);open('reward-detail')}
 const reward=state.entries.find(e=>e.campaignId===rewardId);
 const comingSoon=[{name:'코엑스 케이팝스퀘어',n:'02',code:'COEX',image:'coex-kpop-square',area:'강남',category:'kpop',categoryLabel:'K-pop'},{name:'파르나스 미디어타워',n:'03',code:'PARNAS',image:'parnas-media-tower',area:'강남',category:'watch',categoryLabel:'명품 시계'},{name:'코리아나호텔 K-VISION',n:'04',code:'GWANGHWAMUN',image:'gwanghwamun-koreana-hotel-k-vision',area:'광화문',category:'crypto',categoryLabel:'크립토'}];
 const comingFiltered=comingSoon.filter(e=>(comingArea==='전체'||e.area===comingArea)&&(comingCategory==='전체'||e.category===comingCategory));
 const drawCampaign=campaigns.find(c=>c.id===drawId);
 const drawEntry=state.drawEntries.find(e=>e.campaignId===drawId);
 function openDrawFlow(id:string){setDrawId(id);const e=state.drawEntries.find(e=>e.campaignId===id);if(e?.status==='WINNER_ACTION_REQUIRED'){open('draw-verify')}else if(e?.status==='VERIFIED'){open('draw-shipping')}else{open('draw-status')}}
 const [failure,setFailure]=useState('invalid');const pending=useRef<ReturnType<typeof setTimeout>|null>(null);const busy=useRef(false);
 useEffect(()=>()=>{if(pending.current)clearTimeout(pending.current)},[]);
 const [camera,setCamera]=useState(false);const video=useRef<HTMLVideoElement>(null),stream=useRef<MediaStream|null>(null),frame=useRef<number|null>(null),cameraSession=useRef(0),stateRef=useRef(state);
 stateRef.current=state;const current=campaigns.find(c=>c.id===selected)||campaigns[0];
 const [session,setSession]=useState<Session|null>(null);
 useEffect(()=>{
  supabase.auth.getSession().then(({data})=>{setSession(data.session);setReady(true)});
  const {data:sub}=supabase.auth.onAuthStateChange((_event,newSession)=>{setSession(newSession)});
  return ()=>sub.subscription.unsubscribe();
 },[]);
 async function refreshFromServer(activeSession:Session|null){
  if(!activeSession){setState({...initial});return}
  const [{data:rows},{data:profile}]=await Promise.all([
   supabase.from('reservations').select('*'),
   supabase.from('profiles').select('marketing_opt_in').eq('id',activeSession.user.id).maybeSingle()
  ]);
  const list=rows||[];
  const nextEntries=list.filter(r=>campaigns.find(c=>c.id===r.campaign_id)?.rewardMode==='guaranteed').map(r=>({campaignId:r.campaign_id,reward:campaigns.find(c=>c.id===r.campaign_id)?.reward||'',claimed:r.status==='CLAIMED'}));
  const nextDraw=list.filter(r=>campaigns.find(c=>c.id===r.campaign_id)?.rewardMode==='draw').map(r=>({campaignId:r.campaign_id,status:r.status,...(r.shipping?{shipping:r.shipping}:{})}));
  setState({tier:'member',entries:nextEntries,drawEntries:nextDraw as DemoState['drawEntries'],marketing:profile?.marketing_opt_in===true});
 }
 useEffect(()=>{refreshFromServer(session)},[session]);
 useEffect(()=>{if(session){setModal(m=>{if(m!=='signup')return m;supabase.from('profiles').update({marketing_opt_in:marketing}).eq('id',session.user.id).then(()=>refreshFromServer(session));setTab('wallet');setNotice('로그인됐어요! 참여권이 그대로 연결됐어요.');return signupReturn.current})}},[session]);
 useEffect(()=>{if(notice){const timer=setTimeout(()=>setNotice(''),4500);return()=>clearTimeout(timer)}},[notice]);
 function stopCamera(){cameraSession.current++;stream.current?.getTracks().forEach(t=>t.stop());stream.current=null;if(frame.current)cancelAnimationFrame(frame.current);setCamera(false)}
 useEffect(()=>{if(modal!=='scan')stopCamera();return()=>{stream.current?.getTracks().forEach(t=>t.stop());if(frame.current)cancelAnimationFrame(frame.current)}},[modal]);
 function open(m:Modal){if(pending.current)clearTimeout(pending.current);pending.current=null;busy.current=false;setError('');setModal(m)}
 function openDetail(id:string){setSelected(id);open('detail')}
 function join(value:string){
  if(busy.current)return true;
  if(!session){beginSignup('scan');return true}
  const trimmed=value.trim().toUpperCase();
  if(trimmed==='SEESON-SOLDOUT'){stopCamera();setFailure('sold-out');setError('준비된 리워드가 모두 소진됐어요. 기존에 확보한 리워드는 보관함에서 확인하세요.');setModal('scan-error');return true}
  if(trimmed==='SEESON-EXPIRED'){stopCamera();setFailure('expired');setError('이 QR의 참여 시간이 지났어요. 새로운 QR로 다시 참여해주세요.');setModal('scan-error');return true}
  const matched=campaigns.find(c=>c.code&&c.code===trimmed);
  if(!matched){stopCamera();setFailure('invalid');setError('참여 코드를 확인해주세요.');setModal('scan-error');return true}
  const isDraw=matched.rewardMode==='draw';
  stopCamera();busy.current=true;setModal('checking');setError('');
  supabase.rpc('enter_campaign',{p_campaign_id:matched.id,p_code:value}).then(({error})=>{
   busy.current=false;
   if(error){
    const known:Record<string,{code:string;message:string}>={
     DUPLICATE:{code:'duplicate',message:'이미 참여한 드롭입니다. 내 리워드에서 확인하세요.'},
     SOLD_OUT:{code:'sold-out',message:'준비된 리워드가 모두 소진됐어요.'},
     INVALID_CODE:{code:'invalid',message:'참여 코드를 확인해주세요.'},
     AUTH_REQUIRED:{code:'invalid',message:'로그인 후 다시 시도해주세요.'},
    };
    const mapped=known[error.message]||{code:'invalid',message:'참여를 완료하지 못했어요. 다시 시도해주세요.'};
    setFailure(mapped.code);setError(mapped.message);setModal('scan-error');
    return;
   }
   refreshFromServer(session).then(()=>{
    if(isDraw){setDrawId(matched.id);setModal('draw-success')}else{setModal('success')}
   });
  });
  return true;
 }

 function getReward(id:string){
  setRewardId(id);
  if(!session){beginSignup('reward-detail');return}
  supabase.rpc('claim_reward',{p_campaign_id:id}).then(({error})=>{
   if(error){setNotice('이미 받았거나 받을 수 없는 리워드예요.');return}
   refreshFromServer(session).then(()=>open('receipt'));
  });
 }
 async function startCamera(){setError('');const Detector=(window as any).BarcodeDetector;if(!Detector){setError('이 브라우저는 앱 내 QR 인식을 지원하지 않아요. 아래 데모 참여를 이용해주세요.');return}if(!navigator.mediaDevices?.getUserMedia){setError('카메라를 사용할 수 없어요. 아래 데모 참여를 이용해주세요.');return}const session=++cameraSession.current;try{const media=await navigator.mediaDevices.getUserMedia({video:{facingMode:'environment'}});if(session!==cameraSession.current){media.getTracks().forEach(t=>t.stop());return}stream.current=media;setCamera(true);if(video.current){video.current.srcObject=media;await video.current.play()}const detector=new Detector({formats:['qr_code']});const detect=async()=>{if(session!==cameraSession.current||!video.current)return;try{const results=await detector.detect(video.current);if(results.length){const raw=results[0].rawValue;let value=raw;try{const url=new URL(raw);if(url.origin===location.origin)value=url.searchParams.get('code')||'';else value=''}catch{}if(join(value))return;stopCamera();return}}catch{setError('QR을 인식하지 못했어요. 코드를 입력해 참여해주세요.');stopCamera();return}frame.current=requestAnimationFrame(detect)};frame.current=requestAnimationFrame(detect)}catch{stopCamera();setError('카메라 권한을 허용하지 않았거나 사용할 수 없어요. 데모 코드로 참여할 수 있습니다.')}}
 useEffect(()=>{const params=new URLSearchParams(location.search);const q=params.get('code');if(q){setCode(q);setModal('scan')}},[]);
 useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();try{Promise.resolve(context.registerTool({name:'start_demo_drop',title:'시선 데모 참여 화면 열기',description:'Open the demo QR entry dialog for magok. Does not enter a promotion or send data.',inputSchema:{type:'object',properties:{campaignId:{type:'string',enum:['magok']}},required:['campaignId'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input:unknown)=>{const v=input as any;if(v?.campaignId!=='magok'||Object.keys(v).some(k=>k!=='campaignId'))throw new Error('Only magok is available in this prototype.');setSelected('magok');setCode('SEESON-MAGOK');setError('');setModal('scan');await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));return{screen:'demo_scan',campaignId:'magok',submitted:false}}},{signal:lifecycle.signal})).catch(()=>{})}catch{}return()=>lifecycle.abort()},[]);
 function RewardArt({c,detail}:{c:typeof campaigns[number];detail?:boolean}){
  if(c.id==='magok')return <div className={'reward-art ra-photo'+(detail?' ra-detail':'')}><img src={magok} alt=""/><div className="ra-shade"/><span className="ra-mark">{c.n}</span></div>;
  const Icon=c.category==='watch'?Watch:c.category==='bag'?Handbag:c.category==='crypto'?Bitcoin:Gift;
  return <div className={'reward-art ra-'+c.category+(detail?' ra-detail':'')}><Icon size={detail?54:32} strokeWidth={1.15}/><span className="ra-mark">{c.n}</span></div>;
 }
 function RewardCard({c}:{c:typeof campaigns[number]}){return localize(<button className="reward-card" onClick={()=>openDetail(c.id)}><RewardArt c={c}/><div className="rc-body"><div className="rc-top"><span className="rc-kind">{c.kind}</span><span className="rc-status">{c.status}</span></div><h3>{c.title}</h3><p className="rc-reward">{c.reward}</p><div className="rc-meta"><span><Ticket size={13}/>{c.qty}</span><span><MapPin size={13}/>{c.location}</span></div></div><div className="rc-cta"><span>{c.code?(c.rewardMode==='draw'?'응모 흐름 보기':'참여 흐름 보기'):'제안 살펴보기'}</span><ArrowUpRight size={18}/></div></button>,language)}
 return localize(<div className="app"><header><button className="logo" onClick={()=>setTab('discover')}>시선<span>SISEON</span></button><div className="header-actions"><button className="profile inbox-trigger" aria-label="알림함" onClick={()=>open('notifications')}><Bell size={20}/>{inboxReady&&inboxUnread>0&&<i aria-label="읽지 않은 알림 있음"/>}</button><button className="profile" aria-label={state.tier==='guest'?'로그인':'내 설정'} onClick={()=>open('settings')}><UserRound size={20}/></button></div></header><Tabs value={modal==='scan'?'scan':tab} onValueChange={v=>{if(v==='scan'){open('scan');return}setTab(String(v));setError('')}}><TabsList className="main-nav">{nav.map(({id,label,icon:Icon})=><TabsTrigger key={id} value={id} aria-label={label}><Icon size={28} aria-hidden="true"/></TabsTrigger>)}</TabsList>
<TabsContent value="discover"><main className="discovery episode-discovery"><div className="episode-heading"><div><p className="eyebrow">CITY EPISODES</p><h1>도시의 다음 이야기.</h1></div><button className="profile" aria-label="지도" onClick={()=>open('spots')}><MapPin size={21}/></button></div><div className="reward-grid">{campaigns.map(c=><RewardCard key={c.id} c={c}/>)}</div><p className="episode-disclaimer">마곡 드롭은 실제 지급 없는 체험 · 롤렉스·버킨백·1 BTC는 브랜드·재고·법적 검토 전 제안 단계입니다</p><div className="episode-section"><h2>다음 에피소드</h2><span>COMING SOON</span></div><div className="coming-filters"><div className="coming-filter-row" aria-label="지역 선택">{['전체','강남','광화문'].map(a=><button key={a} aria-pressed={comingArea===a} onClick={()=>setComingArea(a)}>{a}</button>)}</div><div className="coming-filter-row" aria-label="카테고리 선택">{[['전체','전체'],['kpop','K-pop'],['watch','명품 시계'],['apparel','의류'],['crypto','크립토']].map(([id,label])=><button key={id} aria-pressed={comingCategory===id} onClick={()=>setComingCategory(id)}><Tag size={12}/>{label}</button>)}</div></div>{comingFiltered.length===0&&<p className="coming-empty">이 조건에 맞는 다음 에피소드가 아직 없어요.</p>}{comingFiltered.map(e=><button key={e.code} className="episode-card episode-upcoming" onClick={()=>{setMapSpot(e.code==='COEX'?'coex':e.code==='PARNAS'?'parnas':'koreana');open('spots')}}><img src={`https://img.hello-ooh.com/digital_billboard/${e.image}/original/00.webp`} alt={e.name} loading="lazy" onError={event=>{event.currentTarget.style.display='none'}}/><div className="episode-shade"/><div className="episode-top"><span>EP. {e.n} / {e.code}</span><span className="episode-badge episode-badge-muted"><Tag size={11}/>{e.categoryLabel}</span></div><div className="episode-soon">Coming soon<span>{e.name} · {e.area}</span></div><div className="episode-bottom"><span>장소 미리 보기</span><ArrowUpRight size={22}/></div></button>)}<div className="episode-section"><h2>지난 에피소드</h2><span>ARCHIVE</span></div><article className="episode-card episode-ended"><img src={magok} alt="마곡 미디어파사드 참고 이미지"/><div className="episode-shade"/><div className="episode-top"><span>ARCHIVE / DEMO</span><span className="episode-badge">종료</span></div><div className="episode-copy"><h2>마곡의 밤을 담다.</h2><p>종료 화면 예시 · 실제 행사 이력 아님</p></div></article></main></TabsContent>
<TabsContent value="wallet"><main className="collection"><div className="collection-heading"><p className="place">{state.tier==='guest'?'게스트':'시선 멤버'}</p><h1>내 것<span>{state.entries.length}</span></h1></div><div className="wallet-filters" aria-label="리워드 상태">{[['all','전체'],['available','받을 수 있음'],['claimed','수령 완료']].map(([id,label])=><button key={id} aria-pressed={walletFilter===id} onClick={()=>setWalletFilter(id)}>{label}</button>)}</div>{state.entries.length===0?<div className="empty-state"><Gift size={40} strokeWidth={1}/><h2>아직, 빈 주머니.</h2><p>첫 번째 시선을 담아보세요.</p><button className="primary full" onClick={()=>open('scan')}>스캔하기 <ArrowUpRight size={18}/></button></div>:<div className="reward-list">{state.entries.filter(e=>walletFilter==='all'||(walletFilter==='claimed'?e.claimed:!e.claimed)).map(e=><article className="reward" key={e.campaignId}><div className="ticket-top"><span className="reward-status">{e.claimed?'수령 완료':'받을 수 있음'}</span><Ticket size={25} strokeWidth={1}/></div><p className="place">카페 쿠폰</p><h2>{'3,000'}<small>원</small></h2><p className="muted">마곡 나이트 드롭</p><button className="primary full" onClick={()=>viewReward(e.campaignId)}>{e.claimed?'수령 내역 보기':'리워드 자세히 보기'}<ArrowUpRight size={18}/></button><p className="micro">데모 리워드 · 실제 사용 불가</p></article>)}{state.entries.filter(e=>walletFilter==='all'||(walletFilter==='claimed'?e.claimed:!e.claimed)).length===0&&<div className="filter-empty"><Gift size={30}/><p>{walletFilter==='claimed'?'아직 수령한 리워드가 없어요.':'받기 전인 리워드가 없어요.'}</p></div>}</div>}{state.drawEntries.length>0&&<><h2 className="section-subtitle">응모한 캠페인</h2><div className="reward-list">{state.drawEntries.map(e=>{const c=campaigns.find(c=>c.id===e.campaignId);if(!c)return null;return <article className="reward" key={e.campaignId}><div className="ticket-top"><span className="reward-status">{drawStatusLabel(e.status)}</span><Ticket size={25} strokeWidth={1}/></div><p className="place">{c.reward}</p><h2 style={{fontSize:'28px'}}>{c.title}</h2><button className="primary full" onClick={()=>openDrawFlow(e.campaignId)}>{drawCta(e.status)}<ArrowUpRight size={18}/></button><p className="micro">데모 추첨 · 실제 응모·발표·지급 아님</p></article>})}</div></>}<p className="micro collection-note">{state.tier==='guest'?'로그인하면 어떤 기기에서든 이어볼 수 있어요.':'계정에 저장돼 어떤 기기에서든 로그인하면 볼 수 있어요.'}</p></main></TabsContent></Tabs>
 <Dialog open={modal!==null} onOpenChange={v=>{if(!v)open(null)}}><DialogContent showCloseButton={false} className={"seeson-dialog "+(modal==='scan'?'scan-screen':modal==='checking'?'checking-screen':modal==='success'||modal==='draw-success'?'reveal-screen':modal==='spots'?'map-screen':'')}><button className="flow-close" aria-label="닫기" onClick={()=>open(null)}>×</button>


 {modal==='notifications'&&<><DialogTitle>알림</DialogTitle><DialogDescription>놓치지 않도록, 한곳에.</DialogDescription><NotificationCenter language={language} items={inboxItems} readIds={inboxRead} onRead={id=>setInboxRead(prev=>Array.from(new Set([...prev,id])))} onReadAll={()=>setInboxRead(inboxItems.map(i=>i.id))} onOpen={target=>{if(target==='wallet'){setTab('wallet');open(null)}else open('spots')}} events={inboxEvents} rewards={inboxRewards} onEvents={setInboxEvents} onRewards={setInboxRewards}/></>}
 {modal==='reward-detail'&&<><DialogTitle>당신의 리워드.</DialogTitle><DialogDescription>{reward?.claimed?'수령 완료 · 데모':'확정 리워드 · 데모'}</DialogDescription>{reward?<><div className="success-reward reward-detail-ticket"><Gift size={26}/><p>카페 쿠폰</p><h2>{'3,000'}<small>원</small></h2><span>마곡 나이트 드롭</span></div><dl className="reward-facts"><div><dt>수령 조건</dt><dd>무료 회원 이상</dd></div><div><dt>수령 기한</dt><dd>데모 기한 없음</dd></div><div><dt>사용처</dt><dd>실제 사용 불가</dd></div></dl><p className="fine-print">데모에서는 실제 쿠폰이 발급되지 않습니다. 정식 캠페인의 사용처와 유효기간은 상품 확정 후 안내합니다.</p><button className="primary full" onClick={()=>reward.claimed?open('receipt'):getReward(reward.campaignId)}>{reward.claimed?'수령 확인서 보기':state.tier==='guest'?'로그인하고 이 리워드 받기':'이 리워드 받기'}<ArrowRight size={18}/></button>{!reward.claimed&&state.tier!=='guest'&&<details className="demo-scenarios payout-scenarios"><summary>다른 상황 체험</summary><button className="secondary full" onClick={()=>open('payout-error')}>지급 실패 체험</button></details>}</>:<><p>참여 내역이 없습니다.</p><button className="primary full" onClick={()=>open('scan')}>스캔하기</button></>}</>}
 {modal==='payout-error'&&<><div className="flow-status-icon"><Clock size={30}/></div><DialogTitle>지급을 완료하지 못했어요.</DialogTitle><DialogDescription>지급 실패 화면 예시입니다. 확보한 리워드는 유지되며 실제 지급 요청은 발생하지 않았습니다.</DialogDescription><button className="primary full" onClick={()=>getReward(rewardId)}>다시 수령 체험<ArrowRight size={18}/></button><button className="secondary full" onClick={()=>{setTab('wallet');open(null)}}>보관함에서 이어가기</button></>}
 {modal==='receipt'&&<><div className="success-icon"><CheckCircle2 size={46}/></div><DialogTitle>잘 받았어요.</DialogTitle><DialogDescription>리워드 수령 체험이 완료됐습니다.</DialogDescription><div className="receipt-card"><span>SISEON / DEMO</span><h2>{reward?.reward||'카페 쿠폰'}</h2><p>수령 완료</p><small>실제 결제나 쿠폰 지급은 발생하지 않았습니다.</small></div><button className="primary full" onClick={()=>{setTab('wallet');setWalletFilter('claimed');open(null)}}>내 보관함으로<ArrowRight size={18}/></button></>}
 {modal==='settings'&&<><DialogTitle>나의 시선</DialogTitle><DialogDescription>계정과 설정</DialogDescription><div className="my-page"><p className="eyebrow">MY SISEON</p><h2>나의 시선.</h2><section className="account"><div className="avatar"><UserRound size={35}/></div><div><h2>{state.tier==='guest'?'반가워요, 게스트님.':'반가워요, 시선 멤버님.'}</h2><p>{state.tier==='guest'?'참여는 가볍게, 보관은 안전하게.':`로그인됨 · ${session?.user.email||''}`}</p></div>{state.tier==='guest'&&<button className="primary" onClick={()=>beginSignup('settings')}>로그인 <ArrowRight size={18}/></button>}</section><section className="settings"><fieldset className="language-picker"><legend>언어</legend><div>{([['ko','한국어'],['en','English'],['zh-CN','简体中文']] as const).map(([id,label])=><button key={id} type="button" aria-pressed={language===id} onClick={()=>chooseLanguage(id)}>{label}</button>)}</div></fieldset><button onClick={()=>(setTab('wallet'),open(null))}><Gift size={20}/>내 리워드<span>{state.entries.length}개 <ChevronRight size={18}/></span></button><div><label className="check-label"><Checkbox checked={state.marketing} onCheckedChange={v=>{setState({...state,marketing:!!v});if(session)supabase.from('profiles').update({marketing_opt_in:!!v}).eq('id',session.user.id)}}/>마케팅 수신 동의 <small>선택</small></label></div><p className="fine-print">선택 동의 없이도 참여할 수 있습니다. 파트너에게 개인정보를 제공하지 않습니다.</p><button type="button" onClick={()=>setNotice('이 미리보기 링크에서는 기획서 파일이 제공되지 않아요.')}><Download size={20}/>서비스 기획서 (한국어)<span>초안 읽기 <ArrowUpRight size={18}/></span></button>{state.tier==='member'&&<button onClick={()=>open('reset')}><RotateCcw size={20}/>로그아웃<span><ChevronRight size={18}/></span></button>}</section></div></>}
 {modal==='spots'&&<><DialogTitle>다음 시선은 어디에.</DialogTitle><DialogDescription>전광판을 찾고, 그곳으로.</DialogDescription><SpotExplorer initialSpot={mapSpot} language={language} onDemo={()=>openDetail('magok')}/></>}
 {modal==='detail'&&<><DialogTitle>{current.title}</DialogTitle><DialogDescription>{current.kind} · {current.status}</DialogDescription><RewardArt c={current} detail/><p>{current.description}</p><div className="detail-facts"><p><Gift size={17}/>{current.reward}</p><p><Ticket size={17}/>{current.qty}</p><p><MapPin size={17}/>{current.location}</p><p><Clock size={17}/>{current.time}</p></div><p className="fine-print">{current.partner}</p><div className="notice-line">{current.note}</div>{current.code?<button className="primary full" onClick={()=>{setCode('');open('scan')}}>{current.rewardMode==='draw'?'무료 응모 체험':'QR 참여 체험'} <ScanLine size={18}/></button>:<button className="secondary full" onClick={()=>{setSelected('magok');open('detail')}}>지금은 마곡 드롭으로 체험하기</button>}</>}
 {modal==='scan'&&<><DialogTitle>스크린을 담아주세요.</DialogTitle><DialogDescription>{current.location} · 로그인 후 참여</DialogDescription><div className={'scanner '+(camera?'camera-on':'')}><video ref={video} muted playsInline style={{display:camera?'block':'none'}}/>{!camera&&<><ScanLine size={72} strokeWidth={1}/><span>스크린의 QR을 담아주세요</span></>}<div className="scan-corners"/></div><p className="muted">코드를 확인하면 실제로 예약/응모가 접수됩니다. 상품 지급·배송 연동은 아직 준비 중이에요.</p><button className="secondary full" onClick={camera?stopCamera:startCamera}><Camera size={18}/>{camera?'카메라 끄기':'카메라로 QR 읽기'}</button><form onSubmit={e=>{e.preventDefault();join(code)}}><label className="input-label" htmlFor="drop-code">참여 코드</label><div className="code-row"><input id="drop-code" value={code} onChange={e=>setCode(e.target.value)} placeholder={current.code||'SEESON-MAGOK'} autoComplete="off"/><button className="secondary" type="submit">확인</button></div></form>{error&&<p role="alert" className="error">{error}</p>}<button className="primary full" disabled={!ready||!current.code} onClick={()=>join(current.code)}>{current.rewardMode==='draw'?'데모 QR로 바로 응모':'데모 QR로 바로 참여'} <ArrowRight size={18}/></button><p className="fine-print">안전한 보행 구역에 멈춘 뒤 참여해주세요.</p><details className="demo-scenarios"><summary>다른 상황 체험</summary><div><button onClick={()=>join('SEESON-EXPIRED')}>만료된 QR</button><button onClick={()=>join('INVALID')}>잘못된 QR</button><button onClick={()=>join('SEESON-SOLDOUT')}>품절</button></div></details></>}
 {modal==='checking'&&<><div className="checking-orbit" aria-hidden="true"><ScanLine size={40}/></div><DialogTitle>시선을 담는 중.</DialogTitle><DialogDescription role="status">데모 참여를 확인하고 있어요.</DialogDescription><p className="micro">잠시 후 리워드가 나타납니다.</p></>}
 {modal==='scan-error'&&<><div className="flow-status-icon">{failure==='duplicate'?<Gift size={30}/>:<Clock size={30}/>}</div><DialogTitle>{failure==='duplicate'?'이미 담아둔 시선이에요.':failure==='expired'?'다음 QR에서 만나요.':failure==='sold-out'?'이번 리워드는 모두 소진됐어요.':'QR을 다시 확인해주세요.'}</DialogTitle><DialogDescription>{error}</DialogDescription><button className="primary full" onClick={()=>{if(failure==='duplicate'||failure==='sold-out'){setTab('wallet');open(null)}else{setCode('');open('scan')}}}>{failure==='duplicate'||failure==='sold-out'?'내 리워드 보기':'다시 스캔하기'}<ArrowRight size={18}/></button><button className="text-button center" onClick={()=>{setTab('discover');open(null)}}>발견으로 돌아가기</button></>}
 {modal==='success'&&<><div className="success-icon"><CheckCircle2 size={44}/></div><DialogTitle>발견이, 내 것이 되는 순간.</DialogTitle><DialogDescription>마곡 드롭 참여 완료</DialogDescription><div className="success-reward reveal-ticket"><div className="ticket-top"><span>SISEON REWARD / 01</span><Gift size={24}/></div><p>카페 쿠폰</p><h2>{'3,000'}<small>원</small></h2><div className="ticket-divider"/><span>마곡 르웨스트 · 데모 리워드</span></div><button className="primary full" onClick={()=>{if(state.tier==='guest'){setRewardId('magok');beginSignup('reward-detail')}else{setTab('wallet');open(null)}}}>{state.tier==='guest'?'로그인하고 받기':'내 리워드에서 받기'}<ArrowRight size={18}/></button>{state.tier==='guest'&&<button className="text-button center" onClick={()=>{setTab('wallet');open(null)}}>지금은 보관만 할게요</button>}<p className="micro">실제 쿠폰은 발급되지 않는 체험입니다.</p></>}
 {modal==='signup'&&<><DialogTitle>이제, 당신의 것으로.</DialogTitle><DialogDescription>{signupSent?'받은 편지함에서 로그인 링크를 눌러주세요.':'이메일 하나로 로그인해요. 계정이 없으면 자동으로 만들어드려요.'}</DialogDescription>{signupSent?<><div className="signup-benefits"><p><Check size={18}/>{signupEmail} 로 로그인 링크를 보냈어요</p><p><Check size={18}/>메일의 링크를 누르면 자동으로 로그인돼요</p></div><p className="fine-print">메일이 안 보이면 스팸함도 확인해주세요. 링크는 이 기기의 이 브라우저에서 눌러야 로그인됩니다.</p><button className="secondary full" onClick={()=>setSignupSent(false)}>다른 이메일로 다시 받기</button></>:<><div className="signup-benefits"><p><Check size={18}/>참여권을 내 보관함에 연결</p><p><Check size={18}/>리워드 받기</p></div><label className="input-label" htmlFor="signup-email">이메일</label><input id="signup-email" className="field-input" type="email" value={signupEmail} onChange={e=>setSignupEmail(e.target.value)} placeholder="you@example.com" autoComplete="email"/><label className="check-label"><Checkbox checked={marketing} onCheckedChange={v=>setMarketing(!!v)}/>마케팅 수신 동의 <small>선택</small></label><p className="fine-print">이름·휴대폰 번호를 입력할 필요가 없어요. 이메일은 로그인과 리워드 안내에만 사용됩니다.</p>{error&&<p role="alert" className="error">{error}</p>}<button className="primary full" disabled={!signupEmail.trim()||!ready} onClick={()=>{setError('');supabase.auth.signInWithOtp({email:signupEmail.trim(),options:{emailRedirectTo:window.location.origin,shouldCreateUser:true}}).then(({error})=>{if(error){setError('메일 전송에 실패했어요. 이메일 주소를 확인해주세요.');return}setSignupSent(true)})}}>로그인 링크 받기 <ArrowRight size={18}/></button></>}</>}
 {modal==='draw-success'&&drawCampaign&&<><div className="success-icon"><CheckCircle2 size={44}/></div><DialogTitle>응모가 접수됐어요.</DialogTitle><DialogDescription>{drawCampaign.title} · 무료 응모 완료</DialogDescription><div className="success-reward reveal-ticket"><div className="ticket-top"><span>SISEON ENTRY / DEMO</span><Gift size={24}/></div><p>{drawCampaign.reward}</p><h2 style={{fontSize:'30px'}}>발표 예정</h2><div className="ticket-divider"/><span>{drawCampaign.location} · 무료 추첨 데모</span></div><p className="fine-print">발표는 며칠 뒤 이 보관함에서 확인할 수 있어요. 실제 서비스에서는 응모 마감 후 서버가 추첨을 진행합니다. 이 데모는 발표 화면을 바로 미리 볼 수 있게 되어 있어요.</p><button className="primary full" onClick={()=>open('draw-status')}>발표 대기 화면 보기<ArrowRight size={18}/></button><p className="micro">실제 응모나 지급은 발생하지 않는 체험입니다.</p></>}
 {modal==='draw-status'&&drawCampaign&&<><DialogTitle>{!drawEntry||drawEntry.status==='ENTERED'||drawEntry.status==='DRAW_PENDING'?'발표를 기다리고 있어요.':drawEntry.status==='WON'||drawEntry.status==='WINNER_ACTION_REQUIRED'?'당첨을 축하드려요!':drawEntry.status==='NOT_SELECTED'?'이번에는 되지 않았어요.':drawEntry.status==='VERIFIED'?'본인 확인을 완료했어요.':drawEntry.status==='FULFILLING'?'제출을 확인했어요.':drawEntry.status==='DELIVERED'?'배송이 완료됐어요.':'지금은 진행할 수 없어요.'}</DialogTitle><DialogDescription>{drawCampaign.title} · {drawCampaign.reward}</DialogDescription>
  {(!drawEntry||drawEntry.status==='ENTERED'||drawEntry.status==='DRAW_PENDING')&&<><div className="notice-line"><Clock size={17}/>응모가 접수됐어요. 발표는 마감 후 운영팀이 진행하며, 결과가 나오면 이 보관함에서 확인할 수 있어요.</div>{state.tier!=='guest'&&<button className="primary full" onClick={()=>refreshFromServer(session)}>최신 발표 결과 확인하기<ArrowRight size={18}/></button>}<p className="fine-print">아래는 발표 화면을 미리 보는 데모 버튼입니다. 실제 당첨 결과와는 관련이 없어요.</p><button className="secondary full" onClick={()=>{const r=revealDraw(stateRef.current,drawCampaign.id,'won');stateRef.current=r.state;setState(r.state)}}>당첨 발표 체험</button><button className="secondary full" onClick={()=>{const r=revealDraw(stateRef.current,drawCampaign.id,'lost');stateRef.current=r.state;setState(r.state)}}>미당첨 발표 체험</button></>}
  {drawEntry&&(drawEntry.status==='WON'||drawEntry.status==='WINNER_ACTION_REQUIRED')&&<><div className="success-reward reveal-ticket"><div className="ticket-top"><span>SISEON WINNER / DEMO</span><Gift size={24}/></div><p>{drawCampaign.reward}</p><div className="ticket-divider"/><span>본인 확인과 배송 정보 입력이 필요해요.</span></div><button className="primary full" onClick={()=>{if(state.tier==='guest'){beginSignup('draw-status');return}supabase.rpc('acknowledge_win',{p_campaign_id:drawCampaign.id}).then(({error})=>{if(error){setNotice('처리하지 못했어요. 다시 시도해주세요.');return}refreshFromServer(session).then(()=>{setVerifyChecked(false);open('draw-verify')})})}}>{state.tier==='guest'?'로그인하고 당첨 확인하기':'당첨 확인하고 진행하기'}<ArrowRight size={18}/></button></>}
  {drawEntry?.status==='NOT_SELECTED'&&<><p className="fine-print">이번 추첨에는 당첨되지 않았어요. 다음 캠페인에서 다시 만나요.</p><button className="primary full" onClick={()=>{setTab('discover');open(null)}}>다른 캠페인 보러가기<ArrowRight size={18}/></button></>}
  {drawEntry?.status==='VERIFIED'&&<button className="primary full" onClick={()=>open('draw-shipping')}>배송 정보 입력하기<ArrowRight size={18}/></button>}
  {drawEntry?.status==='FULFILLING'&&<><div className="receipt-card"><span>SISEON</span><h2>{drawCampaign.reward}</h2><p>배송 준비 중</p><small>{drawEntry.shipping?.recipient} · {drawEntry.shipping?.address}</small></div><p className="fine-print">배송 정보가 접수됐어요. 발송이 완료되면 이 화면 상태가 자동으로 업데이트돼요.</p><button className="secondary full" onClick={()=>refreshFromServer(session)}>배송 상태 새로고침</button></>}
  {drawEntry?.status==='DELIVERED'&&<div className="receipt-card"><span>SISEON</span><h2>{drawCampaign.reward}</h2><p>배송 완료</p><small>{drawEntry.shipping?.recipient} · {drawEntry.shipping?.address}</small></div>}
  {(!drawEntry||drawEntry.status==='ENTERED'||drawEntry.status==='DRAW_PENDING'||drawEntry.status==='NOT_SELECTED')&&<p className="micro">응모·추첨은 실제로 반영되며, 위 미리보기 버튼만 데모입니다.</p>}</>}
 {modal==='draw-verify'&&drawCampaign&&<><DialogTitle>본인 확인</DialogTitle><DialogDescription>당첨자 확인 절차입니다</DialogDescription><div className="signup-benefits"><p><Check size={18}/>{drawCampaign.reward} 당첨 확정</p><p><Check size={18}/>배송 정보 입력으로 진행</p></div><label className="check-label"><Checkbox checked={verifyChecked} onCheckedChange={v=>setVerifyChecked(!!v)}/>본인 확인을 완료했어요</label><p className="fine-print">정식 서비스에서는 실제 본인확인 절차가 진행되며, 전원에게 금융 KYC를 요구하지 않습니다.</p><button className="primary full" disabled={!verifyChecked} onClick={()=>{supabase.rpc('verify_winner',{p_campaign_id:drawCampaign.id}).then(({error})=>{if(error){setNotice('처리하지 못했어요. 다시 시도해주세요.');return}refreshFromServer(session).then(()=>{setShipRecipient('');setShipPhone('');setShipZip('');setShipAddress('');open('draw-shipping')})})}}>다음: 배송 정보 입력<ArrowRight size={18}/></button></>}
 {modal==='draw-shipping'&&drawCampaign&&<><DialogTitle>배송 정보 입력</DialogTitle><DialogDescription>당첨자에게만 요청하는 최소 정보입니다</DialogDescription><form className="field-group" onSubmit={e=>{e.preventDefault();if(!shipRecipient.trim()||!shipPhone.trim()||!shipZip.trim()||!shipAddress.trim()){setError('수령인·연락처·우편번호·주소를 모두 입력해주세요.');return}setError('');supabase.rpc('submit_shipping',{p_campaign_id:drawCampaign.id,p_recipient:shipRecipient,p_phone:shipPhone,p_zip:shipZip,p_address:shipAddress}).then(({error})=>{if(error){setError('제출하지 못했어요. 다시 시도해주세요.');return}refreshFromServer(session).then(()=>open('draw-status'))})}}><label className="input-label" htmlFor="ship-recipient">수령인</label><input id="ship-recipient" className="field-input" value={shipRecipient} onChange={e=>setShipRecipient(e.target.value)} autoComplete="name"/><label className="input-label" htmlFor="ship-phone">연락처</label><input id="ship-phone" className="field-input" value={shipPhone} onChange={e=>setShipPhone(e.target.value)} autoComplete="tel"/><label className="input-label" htmlFor="ship-zip">우편번호</label><input id="ship-zip" className="field-input" value={shipZip} onChange={e=>setShipZip(e.target.value)} autoComplete="postal-code"/><label className="input-label" htmlFor="ship-address">주소</label><input id="ship-address" className="field-input" value={shipAddress} onChange={e=>setShipAddress(e.target.value)} autoComplete="street-address"/>{error&&<p role="alert" className="error">{error}</p>}<button className="primary full" type="submit">제출하기<ArrowRight size={18}/></button></form><p className="fine-print">입력하신 정보는 배송 목적으로만 사용되며, 이 캠페인의 배송 처리가 끝나면 삭제를 요청할 수 있어요.</p></>}
 {modal==='reset'&&<><DialogTitle>로그아웃할까요?</DialogTitle><DialogDescription>이 기기에서 로그아웃됩니다. 응모·리워드 내역은 계정에 그대로 남아있어요.</DialogDescription><button className="primary full" onClick={()=>{supabase.auth.signOut().then(()=>{setTab('discover');open(null);setNotice('로그아웃했어요.')})}}>로그아웃</button><button className="secondary full" onClick={()=>open(null)}>계속 이용하기</button></>}
 </DialogContent></Dialog>{notice&&<div className="toast" role="status"><CheckCircle2 size={19}/>{notice}</div>}</div>,language)
}
